version: '3.8'

services:
  web:
    build: .
    container_name: apache-php
    ports:
      - "8080:80"
    volumes:
      - ../frontend:/var/www/html
      - ../backend:/var/www/html/backend
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cooperativa
      MYSQL_USER: usuario
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
